# Задача 2.1 Метод Гаусса с выбором главного элемента по столбцу

In [116]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

def PLU_decomposition(A):
    n = A.shape[0]
    
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    P = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return P, L, U


def LowerTriangular_solver(L, b):
	assert np.allclose(L, np.tril(L));  # checks if L is Lower Triangular 
	n = L.shape[0]
	y = np.zeros(n)
	for i in range(n):
		tmp_sum = 0
		for j in range(i):
			tmp_sum += L[i][j] * y[j]
		y[i] = (b[i] - tmp_sum) / L[i][i]
		
	return y


def UpperTriangular_solver(U, y):
	assert np.allclose(U, np.triu(U));  # checks if L is Upper Triangular 
	return LowerTriangular_solver(np.flip(np.flip(U, 1), 0), y[::-1])[::-1]


def solve(A, b):
    P, L, U = PLU_decomposition(A)
    y = LowerTriangular_solver(L, np.dot(P, b)) # перестановка строк b
    x = UpperTriangular_solver(U, y)
    return L, U, P, x

### Квадратная невырожденная матрица

In [117]:
n = 3
A = np.random.rand(n,n).astype(np.float64)
A

array([[0.56255759, 0.74744421, 0.62906831],
       [0.41296807, 0.66440335, 0.05829318],
       [0.11596266, 0.00812188, 0.99802859]])

In [118]:
PLU_decomposition(A)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [ 0.73409029,  1.        ,  0.        ],
        [ 0.20613473, -1.26134338,  1.        ]]),
 array([[ 5.62557594e-01,  7.47444205e-01,  6.29068307e-01],
        [-5.55111512e-17,  1.15711813e-01, -4.03499754e-01],
        [-7.00186234e-17,  0.00000000e+00,  3.59404022e-01]]))

Посмотрим на решение системы $Ax = b$ методом Гаусса

In [119]:
x = np.random.rand(n).astype(np.float64)
pd.DataFrame(x)

0
0  0.008075
1  0.461732
2  0.815113

In [120]:
# Использую матричное умножение для проверки примера. Это не реализация требуемой функции
b = np.dot(A, x.T)
pd.DataFrame(b)

0
0  0.862423
1  0.357627
2  0.818192

Библиотечное решение системы

In [121]:
np_sol = np.linalg.solve(A, b)
pd.DataFrame(np_sol)

0
0  0.008075
1  0.461732
2  0.815113

Кастомное решение системы

In [122]:
my_sol = solve(A, b)[3]
pd.DataFrame(my_sol)

0
0  0.008075
1  0.461732
2  0.815113

Норма разности решений

In [123]:
np.linalg.norm(np_sol - my_sol)

3.878336215544695e-15

### Ещё матрица большего размера

In [124]:
n = 8
A = np.random.rand(n,n).astype(np.float64)

Посмотрим на решение системы $Ax = b$ методом наименьших квадратов

In [125]:
x = np.random.rand(n).astype(np.float64)
pd.DataFrame(x)

0
0  0.924925
1  0.682334
2  0.149404
3  0.725623
4  0.532569
5  0.887934
6  0.028158
7  0.503164

In [126]:
# Использую матричное умножение для проверки примера. Это не реализация требуемой функции
b = np.dot(A, x.T)
pd.DataFrame(b)

0
0  2.175601
1  2.549109
2  1.978502
3  1.965412
4  2.083275
5  2.430153
6  2.449062
7  2.453794

Библиотечное решение системы

In [127]:
np_sol = np.linalg.solve(A, b)
pd.DataFrame(np_sol)

0
0  0.924925
1  0.682334
2  0.149404
3  0.725623
4  0.532569
5  0.887934
6  0.028158
7  0.503164

Кастомное решение системы

In [128]:
my_sol = solve(A, b)[3]
pd.DataFrame(my_sol)

0
0  0.924925
1  0.682334
2  0.149404
3  0.725623
4  0.532569
5  0.887934
6  0.028158
7  0.503164

Норма разности решений

In [129]:
np.linalg.norm(np_sol - my_sol)

3.4964934218771106e-15