# Задача 2.2  Метод Гаусса с выбором главного элемента по строке

In [117]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

def QLU_decomposition(A):
    n = A.shape[1]
    
    U = A.T.copy()
    L = np.eye(n, dtype=np.double)
    Q = np.eye(n, dtype=np.double)
    
    #Loop over columns
    for i in range(n):
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return Q.T, U.T, L.T


def LowerTriangular_solver(L, b):
	assert np.allclose(L, np.tril(L));  # checks if L is Lower Triangular 
	n = L.shape[0]
	y = np.zeros(n)
	for i in range(n):
		tmp_sum = 0
		for j in range(i):
			tmp_sum += L[i][j] * y[j]
		y[i] = (b[i] - tmp_sum) / L[i][i]
		
	return y


def UpperTriangular_solver(U, y):
	assert np.allclose(U, np.triu(U));  # checks if L is Upper Triangular 
	return LowerTriangular_solver(np.flip(np.flip(U, 1), 0), y[::-1])[::-1]


def solve(A, b):
    Q, L, U = QLU_decomposition(A)
    y = LowerTriangular_solver(L, np.dot(Q, b)) # перестановка строк b
    x = UpperTriangular_solver(U, y)
    return L, U, Q, x

### Квадратная невырожденная матрица

In [118]:
n = 3
A = np.random.rand(n,n).astype(np.float64)
A

array([[0.50343312, 0.43212911, 0.222774  ],
       [0.62845596, 0.97632949, 0.9734666 ],
       [0.31451392, 0.68202337, 0.31418181]])

In [119]:
QLU_decomposition(A)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 0.50343312,  0.        ,  0.        ],
        [ 0.62845596,  0.43688521,  0.        ],
        [ 0.31451392,  0.41205579, -0.48084264]]),
 array([[1.        , 0.8583645 , 0.44250963],
        [0.        , 1.        , 1.591651  ],
        [0.        , 0.        , 1.        ]]))

Посмотрим на решение системы $Ax = b$ методом Гаусса

In [120]:
x = np.random.rand(n).astype(np.float64)
pd.DataFrame(x)

0
0  0.455010
1  0.569876
2  0.016733

In [121]:
# Использую матричное умножение для проверки примера. Это не реализация требуемой функции
b = np.dot(A, x.T)
pd.DataFrame(b)

0
0  0.479055
1  0.858629
2  0.537033

Библиотечное решение системы

In [122]:
np_sol = np.linalg.solve(A, b)
pd.DataFrame(np_sol)

0
0  0.455010
1  0.569876
2  0.016733

Кастомное решение системы

In [123]:
my_sol = solve(A, b)[3]
pd.DataFrame(my_sol)

0
0  0.455010
1  0.569876
2  0.016733

Норма разности решений

In [124]:
np.linalg.norm(np_sol - my_sol)

8.617927446923233e-17

### Ещё матрица большего размера

In [125]:
n = 8
A = np.random.rand(n,n).astype(np.float64)

Посмотрим на решение системы $Ax = b$ методом наименьших квадратов

In [126]:
x = np.random.rand(n).astype(np.float64)
pd.DataFrame(x)

0
0  0.306985
1  0.421279
2  0.300836
3  0.604379
4  0.533455
5  0.736683
6  0.172047
7  0.589584

In [127]:
# Использую матричное умножение для проверки примера. Это не реализация требуемой функции
b = np.dot(A, x.T)
pd.DataFrame(b)

0
0  1.411680
1  1.817810
2  1.804504
3  1.554133
4  2.048119
5  1.485364
6  1.971326
7  1.281572

Библиотечное решение системы

In [128]:
np_sol = np.linalg.solve(A, b)
pd.DataFrame(np_sol)

0
0  0.306985
1  0.421279
2  0.300836
3  0.604379
4  0.533455
5  0.736683
6  0.172047
7  0.589584

Кастомное решение системы

In [129]:
my_sol = solve(A, b)[3]
pd.DataFrame(my_sol)

0
0  0.306985
1  0.421279
2  0.300836
3  0.604379
4  0.533455
5  0.736683
6  0.172047
7  0.589584

Норма разности решений

In [130]:
np.linalg.norm(np_sol - my_sol)

5.4274039202379156e-15